swagger: '2.0'
host: http://localhost:8008
basePath: "/api/v1"
tags:
- name: auth
  description: Everything about your Pets
  externalDocs:
    description: Find out more
    url: http://swagger.io
- name: conversations
  description: Access to Petstore orders
- name: friends
  description: Access to Petstore orders
- name: messages
  description: Access to Petstore orders
- name: users
  description: Access to Petstore orders
- name: posts
  description: Access to Petstore orders
 
 
paths:
  "/login":
    post:
      tags:
      - auth
      summary: uploads an image
      description: ''
   
    
  "/register":
    post:
      tags:
      - auth
      summary: uploads an image
      description: ''
    
  "/":
    post:
      tags:
      - conversations
     
    
  "/:query/search":
    get:
      tags:
      - conversations
     
    
   
  
     
    
  
  "/:id/room":
    get:
      tags:
      - conversations
     
    
  "/:id/invite":
    put:
      tags:
      - conversations
     
    
  "/:id/remove_members":
    put:
      tags:
      - conversations
     
    
  "/:id/title":
    put:
      tags:
      - conversations
     
    
  "/:id/cover_image":
    put:
      tags:
      - conversations
     
    
  "/:id/remove_conversation":
    delete:
      tags:
      - conversations
     
    
  "/:userId/user_conversation":
    get:
      tags:
      - conversations
     
    
  "/:id/members":
    get:
      tags:
      - conversations
     
    
  "/friend-requests/:id":
    post:
      tags:
      - friends
     
    
    get:
      tags:
      - friends
     
    
 
  "/friend-requests/sent/:id":
    get:
      tags:
      - friends
     
    
  "/friend-requests/:id/confirm":
    put:
      tags:
      - friends
     
    
  "/friends/:id":
    get:
      tags:
      - friends
     
    
    delete:
      tags:
      - friends
     
    
  "/:conversationId/:page":
      get:
        tags:
        - messages
       
      
  "/:messId":
      get:
        tags:
        - messages
       
      
 
  "/:messageId/update":
      put:
        tags:
        - messages
       
      
 
  "/:messageId/delete":
      delete:
        tags:
        - messages
       
      
  "/:messageId/hidden":
      put:
        tags:
        - messages
       
      
  "/create":
      post:
        tags:
        - posts
       
      
  "/:id":
      get:
        tags:
        - posts
        - users
      put:
        tags:
        - users
      
  "/user/:id":
      get:
        tags:
        - posts
       
  "/:id/like":
      put:
        tags:
        - posts
       
      
  "/:id/unlike":
      put:
        tags:
        - posts
       
      
  "/:id/update":
      put:
        tags:
        - posts
       
  "/:id/delete":
      delete:
        tags:
        - posts
       
      
 
  "/all":
      get:
        tags:
        - conversations
        - users

     
      
     
       
      
  securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
  petstore_auth:
    type: oauth2
    authorizationUrl: https://petstore.swagger.io/oauth/authorize
    flow: implicit
    scopes:
      read:pets: read your pets
      write:pets: modify pets in your account
definitions:
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
